{% set data = load_setup_py_data() %}

package:
  name: dorado
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - numpy
    - scipy
    - matplotlib
    - future
    - tqdm

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - future
    - tqdm

test:
  imports:
    - dorado

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
summary: {{ data['description'] }}
